package com.freelancemarketplace.enums;

public enum ErrorCode {
	USER_NOT_FOUND, WALLET_NOT_FOUND, INSUFFICIENT_BALANCE, TRANSACTION_NOT_FOUND, UNAUTHORIZED_ACCESS, GIG_NOT_FOUND, ORDER_NOT_FOUND, CATEGORY_NOT_FOUND
}
